#!/bin/bash

# 完整部署脚本 - GitHub + Vercel

echo "🚀 JasonStudio Vibe Coding 完整部署指南"
echo "======================================"
echo ""

echo "📋 当前状态："
echo "- ✅ 项目已准备就绪"
echo "- ✅ GitHub仓库已创建"
echo "- ✅ Vercel配置已完成"
echo "- ⏳ 等待网络连接推送到GitHub"
echo ""

echo "🔧 第一步：推送到GitHub"
echo "------------------------"
echo "当网络恢复后，运行以下命令："
echo ""
echo "cd games-portfolio"
echo "git remote add origin https://github.com/jasonstudiocn/games-portfolio.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "🌐 第二步：部署到Vercel"
echo "-----------------------"
echo "方法一：手动部署（推荐）"
echo "1. 访问 https://vercel.com"
echo "2. 使用GitHub账号登录"
echo "3. 点击 'Add New...' → 'Project'"
echo "4. 选择 'jasonstudiocn/games-portfolio'"
echo "5. 使用默认设置，点击 'Deploy'"
echo ""

echo "方法二：使用Vercel CLI"
echo "1. 安装CLI: npm install -g vercel"
echo "2. 登录: vercel login"
echo "3. 部署: vercel --prod"
echo ""

echo "📊 项目信息"
echo "-----------"
echo "- 项目名称：JasonStudio Vibe Coding"
echo "- GitHub仓库：https://github.com/jasonstudiocn/games-portfolio"
echo "- 预期域名：https://games-portfolio-jasonstudiocn.vercel.app"
echo "- 包含游戏：暗区突围、猫咪快跑、网页版我的世界"
echo ""

echo "🎯 部署后测试"
echo "-------------"
echo "基础测试："
echo "- ✅ 页面加载"
echo "- ✅ 响应式设计"
echo "- ✅ 游戏链接"
echo "- ✅ GitHub链接"
echo ""
echo "游戏测试："
echo "- ✅ 暗区突围游戏运行"
echo "- ✅ 猫咪快跑游戏运行"
echo "- ✅ 网页版我的世界游戏运行"
echo ""
echo "交互测试："
echo "- ✅ 键盘快捷键 (Ctrl+1/2/3)"
echo "- ✅ GitHub快捷键 (Ctrl+Shift+1/2/3)"
echo "- ✅ 移动端触摸支持"
echo ""

echo "🔍 故障排除"
echo "-----------"
echo "GitHub推送失败："
echo "- 检查网络连接"
echo "- 验证GitHub token"
echo "- 确认仓库权限"
echo ""
echo "Vercel部署失败："
echo "- 检查vercel.json配置"
echo "- 验证静态文件路径"
echo "- 查看Vercel部署日志"
echo ""

echo "📱 分享链接"
echo "-----------"
echo "部署完成后，您可以分享："
echo "- 作品集链接：Vercel提供的域名"
echo "- GitHub仓库：https://github.com/jasonstudiocn/games-portfolio"
echo "- 各个游戏的GitHub仓库链接"
echo ""

echo "🎉 准备完成！"
echo "-------------"
echo "您的JasonStudio Vibe Coding作品集已准备就绪！"
echo "按照上述步骤完成部署即可上线。"
echo ""